In [53]:
import numpy as np
np.set_printoptions(suppress=True,linewidth=100,precision=2)

In [54]:
loan_data= np.genfromtxt("C:\\Users\mrgup\Downloads\loan-data.csv",delimiter=";",skip_header= 1)
loan_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

# Checking for Null Values


In [55]:
np.isnan(loan_data).sum()

88005

In [56]:
Temporary_Fill= np.nanmax(loan_data)+1
Temporary_Fill

68616520.0

In [57]:
Temporary_Mean=np.nanmean(loan_data,axis=0)
Temporary_Mean

C:\Users\mrgup\AppData\Local\Temp\ipykernel_12636\1585059884.py:1: RuntimeWarning: Mean of empty slice
  Temporary_Mean=np.nanmean(loan_data,axis=0)


array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [58]:
columns_string = np.argwhere(np.isnan(Temporary_Mean)).squeeze()
columns_string

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [59]:
columns_numeric = np.argwhere(np.isnan(Temporary_Mean) == False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

# Splitting the data

In [60]:
loan_data_strings= np.genfromtxt("C:\\Users\mrgup\Downloads\loan-data.csv",
                                     delimiter=";",
                                     usecols=columns_string,
                                     skip_header=1,
                                     dtype=str)
loan_data_strings

array([['May-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', ' 36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [61]:
#importing only numeric data with filling null values
loan_data_numeric = np.genfromtxt("C:\\Users\mrgup\Downloads\loan-data.csv",
                                  delimiter=';',
                                  usecols= columns_numeric,
                                  skip_header=1,
                                  filling_values= Temporary_Fill
                                 )
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

# Setting up Column names


In [62]:
header_full= np.genfromtxt("C:\\Users\mrgup\Downloads\loan-data.csv",
                       delimiter=';',
                       skip_footer= loan_data.shape[0],
                       dtype=str)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [63]:
header_string,header_numeric= header_full[columns_string],header_full[columns_numeric]

In [64]:
header_numeric,header_string

(array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19'),
 array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
        'addr_state'], dtype='<U19'))

# Categorical Data Analysis


## 1- Issue Date Analysis

In [65]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [66]:
#we can replace months by it corresponding numeric occurence
loan_data_strings[:,0] = np.chararray.strip(loan_data_strings[:,0],'-15')
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [67]:
for i in range(13):
    loan_data_strings[:,0] = np.where(loan_data_strings[:,0] == months[i],
                                     i,
                                     loan_data_strings[:,0])

In [68]:
np.unique(loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

## 2- Loan Status Analysis

In [69]:
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [70]:
status_bad= np.array(['','Charged off','Default','Late (31-120 days)'])
status_bad

array(['', 'Charged off', 'Default', 'Late (31-120 days)'], dtype='<U18')

In [71]:
#we can replace bad status by 0 & Good status by 1
loan_data_strings[:,1]=np.where(np.isin(loan_data_strings[:,1],status_bad),0,1)
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

## 3- Term Analysis

In [72]:
np.unique(loan_data_strings[:,2])

array(['', ' 36 months', ' 60 months'], dtype='<U69')

In [73]:
#we can strip 'months' from each element
loan_data_strings[:,2]=np.chararray.strip(loan_data_strings[:,2],' months')

In [74]:
#for null values we assume 60 months loan term
loan_data_strings[:,2]= np.where(loan_data_strings[:,2]=='',
                                '60',
                                loan_data_strings[:,2])

In [75]:
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

## 4- Grade & SubGrade Anlaysis

In [76]:
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [77]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [78]:
#same conclusion can be obtained from both columns
#replacing null values in sub grade by its corresponding values + 5 in Grade
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4]= np.where((loan_data_strings[:,4]=='') & (loan_data_strings[:,3]==i),
                                    i+'5',
                                    loan_data_strings[:,4])
np.unique(loan_data_strings[:,4],return_counts = True)
    

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [79]:
#hence null values are very less so it will not much affect our analysis
#replacing null with new GRADE 'H1'
loan_data_strings[:,4] = np.where(loan_data_strings[:,4]=='',
                                 'H1',
                                 loan_data_strings[:,4])
np.unique(loan_data_strings[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [80]:
loan_data_strings= np.delete(loan_data_strings,3,axis=1)

In [81]:
header_string= np.delete(header_string,3)

In [82]:
header_string

array(['issue_d', 'loan_status', 'term', 'sub_grade', 'verification_status', 'url', 'addr_state'],
      dtype='<U19')

In [83]:
#converting grade to corresponding numeric value
keys = list(np.unique(loan_data_strings[:,3]))
values = list(range(1,np.unique(loan_data_strings[:,3]).shape[0]+1))
dict_sub_grade = dict(zip(keys,values))
dict_sub_grade
            

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [84]:
for i in np.unique(loan_data_strings[:,3]):
    loan_data_strings[:,3] = np.where(loan_data_strings[:,3] == i,
                                     dict_sub_grade[i],
                                     loan_data_strings[:,3])
np.unique(loan_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

## 4- Verification Status Analysis

In [85]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [86]:
loan_data_strings[:,4]= np.where((loan_data_strings[:,4] == '') | (loan_data_strings[:,4]== 'Not Verified'),
                                 0,
                                 1)


In [87]:
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

## 5- url Analysis

In [88]:
np.unique(loan_data_strings[:,5])

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=12606806',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=13026045',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=1312426', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8138291',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8214572',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=849994'], dtype='<U69')

In [89]:
loan_data_strings[:,5]= np.chararray.strip(loan_data_strings[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [90]:
np.unique(loan_data_strings[:,5])

array(['12606806', '13026045', '1312426', ..., '8138291', '8214572', '849994'], dtype='<U69')

In [91]:
np.array_equal(loan_data_numeric[:,0].astype(dtype=np.int32),loan_data_strings[:,5].astype(dtype=np.int32))

True

In [92]:
#column url also give same information as column id
loan_data_strings= np.delete(loan_data_strings,5,axis=1)
header_string= np.delete(header_string,5)

In [93]:
loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [94]:
header_string[5]

'addr_state'

In [95]:
header_string

array(['issue_d', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

## 6- Address State Analysis


In [96]:
loan_data_strings= np.delete(loan_data_strings,5,axis=1)  
header_string= np.delete(header_string,5)

In [97]:
loan_data_strings

array([['5', '1', '36', '13', '1'],
       ['0', '1', '36', '5', '1'],
       ['9', '1', '36', '10', '1'],
       ...,
       ['6', '1', '36', '5', '1'],
       ['4', '1', '36', '17', '1'],
       ['12', '1', '36', '4', '0']], dtype='<U69')

In [98]:
loan_data_strings= loan_data_strings.astype(dtype=np.float32)
loan_data_strings

array([[ 5.,  1., 36., 13.,  1.],
       [ 0.,  1., 36.,  5.,  1.],
       [ 9.,  1., 36., 10.,  1.],
       ...,
       [ 6.,  1., 36.,  5.,  1.],
       [ 4.,  1., 36., 17.,  1.],
       [12.,  1., 36.,  4.,  0.]], dtype=float32)

# Numerical Data Analysis 

##  Substitute Filler Values by Mean of each Column

In [99]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

### 1- ID

In [100]:
np.isin(loan_data_numeric[:,0],Temporary_Fill).sum()

0

In [101]:
np.isnan(loan_data_numeric[:,0]).sum()

0

### 2- Funded Amount

In [102]:
#replacing temporary fill in funded Amount by minimum value of funded amount
loan_data_numeric[:,2]= np.where(loan_data_numeric[:,2] == Temporary_Fill,
                                np.nanmin(loan_data[:,4]),
                                loan_data_numeric[:,2])

In [103]:
np.isin(loan_data_numeric[:,2],Temporary_Fill).sum()

0

In [105]:
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

### 3-  loan_amnt,  int_rate, installment, total_pymnt Analysis

In [183]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [185]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [107]:
loan_data_numeric[:,1] = np.where(loan_data_numeric[:,1] == Temporary_Fill,
                                   np.nanmax(loan_data[:,2],axis=0),
                                   loan_data_numeric[:,1]
                                     )


In [110]:
np.max(loan_data_numeric[:,1])

35000.0

In [111]:
#for int_rate
loan_data_numeric[:,3] = np.where(loan_data_numeric[:,3] == Temporary_Fill,
                                   np.nanmax(loan_data[:,6],axis=0),
                                   loan_data_numeric[:,3])
np.max(loan_data_numeric[:,3])

28.99

In [112]:
#for intsallment
loan_data_numeric[:,4] = np.where(loan_data_numeric[:,4] == Temporary_Fill,
                                   np.nanmax(loan_data[:,7],axis=0),
                                   loan_data_numeric[:,4]
                                     )


In [113]:
#for total_pamnt
loan_data_numeric[:,5] = np.where(loan_data_numeric[:,5] == Temporary_Fill,
                                   np.nanmax(loan_data[:,13],axis=0),
                                   loan_data_numeric[:,5]
                                     )


# Exporting Data set

In [114]:
loan_data_numeric.shape

(10000, 6)

In [115]:
loan_data_strings.shape

(10000, 5)

In [116]:
header_numeric.shape

(6,)

In [117]:
header_string.shape

(5,)

In [120]:
header_full= np.hstack((header_numeric,header_string))
header_full

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'issue_d',
       'loan_status', 'term', 'sub_grade', 'verification_status'], dtype='<U19')

In [121]:
loan_data = np.hstack((loan_data_numeric,loan_data_strings))
loan_data


array([[48010226.,    35000.,    35000., ...,       36.,       13.,        1.],
       [57693261.,    30000.,    30000., ...,       36.,        5.,        1.],
       [59432726.,    15000.,    15000., ...,       36.,       10.,        1.],
       ...,
       [50415990.,    10000.,    10000., ...,       36.,        5.,        1.],
       [46154151.,    35000.,    10000., ...,       36.,       17.,        1.],
       [66055249.,    10000.,    10000., ...,       36.,        4.,        0.]])

In [122]:
#sorting data set
loan_data = loan_data[np.argsort(loan_data[:,0])]
loan_data

array([[  373332.,     9950.,     1000., ...,       36.,       21.,        0.],
       [  575239.,    12000.,    12000., ...,       60.,       25.,        1.],
       [  707689.,    10000.,    10000., ...,       36.,       13.,        1.],
       ...,
       [68614880.,     5600.,     5600., ...,       36.,        8.,        1.],
       [68615915.,     4000.,     4000., ...,       36.,       10.,        1.],
       [68616519.,    21600.,    21600., ...,       36.,        3.,        0.]])

In [123]:
loan_data = np.vstack((header_full,loan_data))
loan_data

array([['id', 'loan_amnt', 'funded_amnt', ..., 'term', 'sub_grade', 'verification_status'],
       ['373332.0', '9950.0', '1000.0', ..., '36.0', '21.0', '0.0'],
       ['575239.0', '12000.0', '12000.0', ..., '60.0', '25.0', '1.0'],
       ...,
       ['68614880.0', '5600.0', '5600.0', ..., '36.0', '8.0', '1.0'],
       ['68615915.0', '4000.0', '4000.0', ..., '36.0', '10.0', '1.0'],
       ['68616519.0', '21600.0', '21600.0', ..., '36.0', '3.0', '0.0']], dtype='<U32')

In [124]:
np.savetxt('loan_project_cleaned.csv',
           loan_data,
           delimiter = ';',
           fmt = '%s')